#!/bin/bash


PS1="[\u@\h \W]\$ "


PATH=code/:code/bin/:code/utilities/STAR/:code/utilities/sratoolkit/:code/utilities/cufflinks/:code:code/bin:code/utilities:code/utilities/CPAT/:code/utilities/fastqc/:code/utilities/subread:$PATH


PYTHONPATH=$HOME/utilities/python_software/local/apps/python/2.7.3/lib/python2.7/site-packages:$PYTHONPATH

export LC_ALL=C
export PATH
export PYTHONPATH

export PERL5LIB=$HOME/lib
export EDITOR="/usr/local/bin/mate -w"

module load samtools/0.1.19
module load r/3.3.0
