#!/bin/bash

if [ "$#" -ne 1 ]; then
        printf "\n\n###### Usage\n\n"
        printf "$0 <INPUT GTF file>\n\n"
        exit
fi

INP=$1
TEMP1=$(mktemp)
TEMP2=$(mktemp)

cat $1 | awk '$3~/exon/'| perl -F/\\t/ -lane '@des=split(/ \"|\";\s{0,1}/,$F[8]);for($i=0;$i<@des;$i=$i+2){if($des[$i]=~/gene_id/){$gene_id=$des[$i+1]}elsif($des[$i]=~/gene_name/){$gene_name=$des[$i+1]}else{}}print "$gene_name\t$gene_id"' | sort | uniq | mergeuniq -merge > $TEMP1

cat $TEMP1 | grep " " | key-expand | cols -t 1 0 | awk '{print $1"\t"$1":"$2}' > $TEMP2 

cat $TEMP1 | grep -v " " | cols -t 1 0 >> $TEMP2

cat $TEMP2 | sort -k1,1 > ${INP%.*}.id2name.txt
