#!/bin/bash

source code/custom-bashrc

if [ "$#" -lt 3 ]; then
	printf "\n\n###### Usage\n\n"
	printf "$0 <PARAMS file> <OUTPUT_DIR> <INPUT_DIR> [Optional: Sample Name] \n\n"
	exit
fi

date




#########################
# input
PARAMS=$1
OUT_DIR=`echo $2 | sed 's/\/\//\//g'`
INP_DIR=$3
SAMPLE=$4



#########################

IFS=$'\n'

params=`cat $PARAMS | grep -P "^fastq-link\t" | cut -f2 | tr ' ' '\n' | grep -v "^#"`

#########################
# read input
if [ ! -z "`cat $PARAMS | grep -P "^fastq-link\t"`" ]
then

for FILE in $params
do
	mylink=`head -1 $FILE`
	if [ -d $mylink ]
	then
		dirname=`basename $FILE | sed 's/.txt//g'`
		ln -sf $mylink $OUT_DIR/$dirname
		for record in `cat $FILE | grep -v "\/"`
		do
			sample_name=`echo $record | cut -f1`		
			if [ "$sample_name" == "$SAMPLE" ] || [ -z "$SAMPLE" ]
			then
				if [ ! -d $OUT_DIR/$sample_name ]
				then
					mkdir -p $OUT_DIR/$sample_name
				fi
				identifier=`echo $record | cut -f2`
				printf "\n\n***** Linking $sample_name To $mylink/${identifier}*...\n"
				for myfastq in `ls $OUT_DIR/$dirname/* | grep "$identifier"`
				do
					suffix=`echo $myfastq | sed 's/'$identifier'/\t/g' | cut -f2`
					ln -sf ../$dirname/`basename $myfastq` $OUT_DIR/$sample_name/${sample_name}${suffix}
				done
			fi			
		done

##########################
# for SRA download linking
	elif [ ! -z `cat $FILE | cut -f2 | grep SRX | tr '\n' 'XXXX'` ]
	then
		
for record in `cat $FILE | grep SRX`
do
        name_sample=`echo $record | cut -f1`
        id_sample=`echo $record | cut -f2`
if [ "$name_sample" == "$SAMPLE" ] || [ -z "$SAMPLE" ]
then
        link_sample="ftp://ftp-trace.ncbi.nlm.nih.gov/sra/sra-instant/reads/ByExp/sra/SRX/${id_sample:0:6}/$id_sample/"
        ID_RUNS=(`curl -sS $link_sample | sed -r 's/\s+/\t/g' | cut -f9 `)
        num_run=0


#########################
# check if SRA download complete
        if [ ! -d $INP_DIR/$name_sample ]
        then
                printf "\n\nERROR! $INP_DIR/${name_sample} not found!\n\n"
                exit 1
        fi

        if [ ! -d $OUT_DIR/$name_sample ]
        then
                mkdir $OUT_DIR/$name_sample
        fi


        for id_run in "${ID_RUNS[@]}"
        do
                ((num_run++))
                num_run=$(printf "%03d" $num_run)
                link_run=${link_sample}${id_run}"/"
                ID_FILES=(`curl -sS $link_run | sed -r 's/\s+/\t/g' | cut -f9 `)
                num_read=0
                for name_file in "${ID_FILES[@]}"
                do
                        link_file=${link_run}${name_file}"/"
                        id_file=${name_file%.*}

printf "\n\n***** Linking $name_sample To $INP_DIR/$name_sample/${id_file}...\n"

ln -sf ../`basename $INP_DIR`/$name_sample/${id_file}_1.fastq.gz $OUT_DIR/$name_sample/${name_sample}_L${num_run}_R1.fastq.gz
if [[ -f $INP_DIR/$name_sample/${id_file}_2.fastq.gz ]]
then
ln -sf ../`basename $INP_DIR`/$name_sample/${id_file}_2.fastq.gz $OUT_DIR/$name_sample/${name_sample}_L${num_run}_R2.fastq.gz
fi

                done
        done
fi
done
	else
		printf "\n\nERROR in INPUT file!\n\n"
		exit 1
	fi
done

fi

#########################
date
#end
