#!/bin/bash

source code/custom_bash_profile	# shell settings

if [ "$#" -ne 4 ] && [ "$#" -ne 3 ]
then
        printf "\n\n###### Usage\n\n"
        printf "$0 [Optional: Threads (Default 6)] <PARAMS file> <OUTPUT DIR> <GROUP NAME>\n\n"
        exit 1
fi

if [[ $1 =~ ^[[:digit:]]{1,2}$ ]];then NSLOTS=$1;shift
elif [[ $NSLOTS == "" ]]; then NSLOTS=6; fi

PARAMS=$1
OUT_DIR=$2
GROUP=$3

params=`cat $PARAMS | grep "^DESeq2" | cut -f2`

cd $OUT_DIR


align_summary alignment/*/STAR.Log.final.out > align_summary.txt

summarize_raw_count alignment/*/STAR.count.txt > raw_count.txt

#qsub -b Y -cwd -j Y -pe threaded 8 /local/apps/R/3.2.0/bin/Rscript ~/utilities/yixiao_scripts/count2fpkm.r ../referenceFiles/Homo_sapiens.GRCh37.\?\?.gtf ../referenceFiles/Homo_sapiens.GRCh37.\?\?.id2name.txt ../alignment/raw_count.txt

install_R_packages.r

ID2NAME=${params%.*}.id2name.txt
if [ ! -f $ID2NAME ] 
then
	gtf_id2name ${params}
fi 

DESeq2.r $params $ID2NAME meta_data/group_info.txt $GROUP raw_count.txt

DESeq_post_v3.r $GROUP/${GROUP}_Rscript.RData align_summary.txt meta_data/signature.txt meta_data/target.txt

rm -rf align_summary.txt Rplots.pdf

zip -r ${GROUP}_Report.zip $GROUP fpkm_table.txt norm_count.txt raw_count.txt

ln -s $OUT_DIR/${GROUP}_Report.zip ../../${GROUP}_Report.zip
