#!/bin/bash

if [ -f code/custom_bash_profile ]; then source code/custom_bash_profile; fi # shell settings

TEMP="$#"
FILE_COUNT=$((TEMP*2))

INDEX="1"

for i in $(seq 2 2 $FILE_COUNT)
do
	INDEX=${INDEX}","${i}
done

paste $@ | cut -f${INDEX} 
