#!/bin/bash

source code/custom-bashrc

if [ "$#" -ne 4 ] && [ "$#" -ne 3 ]
then
        printf "\n\n###### Usage\n\n"
        printf "$0 [Optional: Threads (Default 6)] <PARAMS file> <OUTPUT DIR> <GROUP NAME>\n\n"
        exit 1
fi

if [[ $1 =~ ^[[:digit:]]{1,2}$ ]];then NSLOTS=$1;shift
elif [[ $NSLOTS == "" ]]; then NSLOTS=6; fi

PARAMS=$1
OUT_DIR=$2
group_info=$3
GROUP=$4
group_sheet=`basename $group_info | sed 's/\.txt$//g'`

params=`cat $PARAMS | grep "^DESeq2" | cut -f2`

if [ `cat ${GROUP}.out | wc -l` -eq 1 ]; then exec >> $GROUP.out;else exec > $GROUP.out; fi
exec 2>&1

cd $OUT_DIR

mkdir -p $group_sheet

if [ ! -f $group_sheet/align_summary.txt ]
then
align_summary `cat $group_info | cut -f1 | skipn 1 | sed 's/^/alignment\//g' | sed 's/$/\/STAR.Log.final.out/g' | tr '\n' ' '` > $group_sheet/align_summary.txt
fi

if [ ! -f $group_sheet/raw_count.txt ]
then
summarize_raw_count `cat $group_info | cut -f1 | skipn 1 | sed 's/^/alignment\//g' | sed 's/$/\/STAR.count.txt/g' | tr '\n' ' '` > $group_sheet/raw_count.txt
fi

#qsub -b Y -cwd -j Y -pe threaded 8 /local/apps/R/3.2.0/bin/Rscript ~/utilities/yixiao_scripts/count2fpkm.r ../referenceFiles/Homo_sapiens.GRCh37.\?\?.gtf ../referenceFiles/Homo_sapiens.GRCh37.\?\?.id2name.txt ../alignment/raw_count.txt

install_R_packages.r

ID2NAME=${params%.*}.id2name.txt
if [ ! -f $ID2NAME ] 
then
	gtf_id2name ${params}
fi 

DESeq2.r $params $ID2NAME $group_info $GROUP $group_sheet/raw_count.txt

DESeq_post_v3.r $group_sheet/$GROUP/${GROUP}_Rscript.RData $group_sheet/align_summary.txt meta_data/signature.txt meta_data/target.txt

rm -rf Rplots.pdf

#zip -r ${group_sheet}_Report.zip $group_sheet

#ln -s $OUT_DIR/${group_sheet}_Report.zip ../../${group_sheet_Report}.zip
